import React from 'react';
import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Providers } from './providers';
import { Toaster } from "@/components/ui/toaster"
import { ProjectProvider } from '@/contexts/ProjectContext';
import { SidebarProvider } from '@/contexts/SidebarContext';

export const metadata: Metadata = {
  title: "Pulser",
  description: "Generated by pulser",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <ClerkProvider>
            <ProjectProvider>
              <Providers>{children}</Providers>
              <Toaster />
            </ProjectProvider>
          </ClerkProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
